use_frameworks!

platform :ios, '10.0'

target 'CalendarDatePicker_Example' do
  pod 'CalendarDatePicker', :path => '../'

  target 'CalendarDatePicker_Tests' do
    inherit! :search_paths

    
  end
end
